### PR TITLE
Adding CONVERGE video to homepage

### LINKED ISSUE #1424: Add   ELIXIR CONVERGE - The why of research data management video to landingpage
**Description**

### PR DESCRIPTION
**Pull request by bedroesb**
As requested in the editorial meeting: 

image

I am not so sure about the subtitle do, can we have something more friendly? 

This will close #1424

### CODE REVIEW

**Comment by bianchini88** [comment]
Do we actually need the subtitle? Isn't the thumbnail self-explanatory enough?

**Comment by marikapop** [comment]
Research Data management at glance?

It is more visible on black. But I personally prefer with subtitle. Without it, I personally, ignore video without reading its thumbnail :\

**Comment by bianchini88** [comment]
@bedroesb I like more the thumbnail with the image, it gives the idea it is going to be an informative but somehow funny cartoon and not a presentation/monologue of some sort.
But it is only an opinion, obviously. I like the subtitle @marikapop is suggesting, though.

**Comment by bedroesb** [comment]
@bianchini88 oh the first one being black is because I accidently clicked on it! "Research Data management at glance" is definitely better than what we have now !

**Comment by martin-nc** [comment]
I think the title is good, too - it makes the content more obvious to search engines and it's a more accessible (assuming it's an `<h2>` or something). Yes, and keep the picture. That's my vote!

**Comment by bedroesb** [comment]
image

Something like this?

**Comment by bianchini88** [comment]
I would capitalise as either "Research Data Management" or "Research data management".

**Comment by bianchini88** [comment]
(I will have to disappear for a meeting now)

**Comment by marikapop** [comment]
I vote for "Research Data Management..." it kind of give hint to "RDM"

**Comment by bedroesb** [comment]
Done!

**Comment by bedroesb** [comment]
Somebody else can pull the trigger to merge ;)

**Comment by marikapop** [comment]
@bedroesb is it want you wanted form somebody: click on "Squash and merge"?

**Comment by bedroesb** [comment]
yes!

**Comment by bedroesb** [comment]
Woopsie I see now that I forgot to take the capital version "Research Data Management" I changed it straight in master ;)

**Comment by Nazeeefa** [comment]
We do need caption, in addition to the subtitle, as it's especially useful for screen readers as well for SEO. The 'Research Data Management at glance' doesn't tell if what's next is a video or text. (btw I visited RDMkit with VoiceOver screen reader on Mac and it was difficult to navigate the main page).

**Pull request merged**
