### PR TITLE
Marine metagenomics tool assembly

### LINKED ISSUE #614: Marine metagenomics tools assembly
**What topic do you wish to add?**
A tool assembly page describing the assembly of RDM tools to support Marine Metagenomics projects.

**Are there existing pages in the RDMkit website related to the requested page?**
https://rdmkit.elixir-europe.org/marine_metagenomics.html

**Resources**
https://docs.google.com/document/d/1GN7p55ZotNNPtX85B-h6yZJwxvNXMUHOPjabIcBZGus/edit

**Context**
This page request is issued as part of the tool assembly contentathon.

### PR DESCRIPTION
**Pull request by lauportell**
Closes #614

This is the page for the marine metagenomics tool assembly.
- The image will be added by @korbinib
- I will be adding the tools to the tool table with the marine_assembly tag @bedroesb.

### CODE REVIEW

**Review by korbinib — APPROVED** [review]

**Comment by korbinib** [comment]
@bedroesb removed the country specific instances (DSW, galaxy) from the tools google sheet for now.

**Review by bedroesb — APPROVED** [review]

**Comment by bedroesb** [comment]
@korbinib you did that or did I do that ? :)

**Comment by korbinib** [comment]
@bedroesb  I did, sorry for the confusion. Think this is what we agreed on did we?

**Comment by bedroesb** [comment]
@korbinib I think that is fine @floradanna ?

**Comment by bedroesb** [comment]
@lauportell Are you ready with the tools in the spreadsheet? than I make an update.

**Comment by korbinib** [comment]
Yes the tools should be ready :)

**Comment by bedroesb** [comment]
tools updated with #648

**Pull request merged**
