### PR TITLE
Change title to Creating a data workflow diagram

### PR DESCRIPTION
**Pull request by bedroesb**
THe current title is not reflecting the content of the page

### CODE REVIEW

**Comment by bedroesb** [comment]
@vildead

**Comment by Nazeeefa** [comment]
@bedroesb Thanks for suggesting the title ‘Creating a workflow diagram’! :) To refine it, it would be helpful if @vildead can kindly clarify if a diagram is suggested to represent a flow of project data or structured flow of data analysis? Based on the page content, it seems former (not data analysis workflows in a bioinformatics context), so incorporating ‘project’ in the title might be more precise. Easier and better approach to this is mentioning clearly in page text the definition of workflow in a context of data management (to avoid confusion with bioinformatics definition). Sorry for any inconvenience from my side.

**Review by marikapop — APPROVED** [review]

**Comment by bedroesb** [comment]
@Nazeeefa I agree that this is indeed some context that would be nice to have! I will go ahead and merge this to make sure the current page url does not get used to much :)

**Comment by bedroesb** [comment]
@marikapop thanks!

**Comment by bedroesb** [comment]
Or wait I read to quickly, @ nazeefa, would you chaneg the title to Creating a data project diagram?

**Comment by marikapop** [comment]
> Or wait I read to quickly, @nazeefa, would you change the title to Creating a data project diagram?

Now I do not like this title :) It sounds to me like Creating a diagram of a data project.
What about Creating a project dataflow diagram or simpler Creating a dataflow diagram.

**Comment by bedroesb** [comment]
@marikapop I like that last one!

**Comment by bedroesb** [comment]
@marikapop Could you check with @vildead if he is ok with this change?

**Comment by vildead** [comment]
nice! Thank you for the changes. Indeed, its more about making a diagram

**Pull request merged**
