### PR TITLE
Update news.yml

### PR DESCRIPTION
**Pull request by bianchini88**
Added linked PR to new item

### CODE REVIEW

**Comment by bedroesb** [comment]
@bianchini88 I don't think it is relevant to link the PR in this news item since it is not linked to work that was done for the newsitem. (there is no added value/content in the pull request)

**Comment by bianchini88** [comment]
@bedroesb I do not disagree with what you are saying. It is just that from the graphical point of view it looks like someone forgot to add that piece of information (maybe it is only in my head).

**Review by Nazeeefa — APPROVED** [review]

**Comment by Nazeeefa** [comment]
I approved because it is now consistent with how other news items about new pages are published.

**Comment by bedroesb** [comment]
I don't have a strong enough opinion to block this one ;)

**Pull request merged**
