### PR TITLE
Updates to publish Ireland national resources page

### PR DESCRIPTION
**Pull request by Nazeeefa**
Update data_management.yml; adding Ireland national resources page to 'data management' sidebar.
Adding page contributors to main contributors list.

### CODE REVIEW

**Comment by bedroesb** [comment]
@clearysi one last thing! Could you provide your information (only name and github ID is mandatory) for in the CONTRIBUTORS file? This is mandatory for coordinators of a national resource page so we are able toc ontact the back:

```yml
Full Name:
   git: 
   email: 
   orcid: 
   affiliation:
```

**Comment by Nazeeefa** [comment]
Hi @bedroesb these are already added by @clearysi I believe. See line 501-505 here https://github.com/elixir-europe/rdmkit/blob/Nazeeefa-ireland-rdm-1/_data/CONTRIBUTORS.yaml

**Comment by clearysi** [comment]
Hi @bedroesb  and @Nazeeefa, yes that is correct. I have already added my name to CONTRIBUTERS.yaml. Thanks!

**Comment by bedroesb** [comment]
oh I missed them, sorry! I guess it is time to merge this PR than!

**Pull request merged**
