### PR TITLE
Move to new version of ETT

### PR DESCRIPTION
**Pull request by bedroesb**
This will bring following changes:

- "Tools and resources on this page" as heading
- Update Bootstrap to 5.3.2 and fix warning in build
- Only show pagination and search in datatables when relevant
- Add hide sidebar function
- Update countries automatically as it is now part of the theme
- Fix topnav highlight bug when toc: false

### CODE REVIEW

**Comment by Nazeeefa** [comment]
> Add hide sidebar function

Do you mean the one on the left or the navigation pane in each sub-page?

**Comment by bedroesb** [comment]
This is just a feature that the theme now decently supports. When no sidebar is specified, none will be given (the on one the left) and the content will take on the whole width of the page. In the past this would leave an empty gap.

**Comment by bedroesb** [comment]
Not really relevant for the RDMkit since we always specify a sidebar

**Review by martin-nc — APPROVED** [review]
Look fine to me!

**Pull request merged**
