### PR TITLE
Update metadata_management.md

### PR DESCRIPTION
**Pull request by korbinib**
Fighting https related link rot

### CODE REVIEW

**Review by bedroesb — APPROVED** [review]

**Review by bianchini88 — APPROVED** [review]

**Comment by bedroesb** [comment]
@korbinib did you also change the google doc spreadsheet? Is important :)

**Comment by korbinib** [comment]
@bedroesb did a bit more of link maintenance and updated the spreadsheet. I think we have to enable the link checker again.

**Comment by bedroesb** [comment]
@korbinib If we have one with not many false positives, please yes :) or if someone wants to maintain a white-list ...
HTML spoofer from Jekyll is not really great

**Comment by bedroesb** [comment]
These are great fixes! Thanks

**Pull request merged**
