### PR TITLE
Support page

### LINKED ISSUE #499: Institutes branding page
A page were the participating institutes are profiled.

### PR DESCRIPTION
**Pull request by bedroesb**
This PR will add a branding page with all the institutes

Closes #499 
Screenshot from 2021-04-23 13-40-14
Screenshot from 2021-04-23 13-40-25

We will have to decide on location of page (within community or at top level of about? and the name of the page.

@frederikcoppens would help out in the text on this page

todo:
- [x] Documentation on how to add a contributor
- [x] centering the logo's on the Y axis

### CODE REVIEW

**Comment by floradanna** [comment]
I think that a good location of page is within community.

**Comment by frederikcoppens** [comment]
I agree this fits under community. I would first make sure the institutes of the editors are represented, looks like a good start.

**Comment by bedroesb** [comment]
@frederikcoppens I also added a funders page. Should we add a line on the page like: `Do you think you institute should be mentioned here? [Contact us](rdm-editors@elixir-europe.org) for a request.` ?

**Comment by ingejonassen** [comment]
Add Research Council of Norway as funder https://www.forskningsradet.no/en/ 
research_council_of_norway

**Pull request merged**
