### PR TITLE
Fairtracks assembly

### LINKED ISSUE #1418: FAIRtracks tool assembly
**What topic do you wish to add?**
FAIRtracks tools assembly

**Context**
It was agreed to work on this page at the BioHackathon 2021 by virtual participants 
(Bosl, Bianchini, Gundersen). An associated domain page was also meant to be produced,
content gaps (https://github.com/elixir-europe/rdmkit/issues/1010) and a general lack of capacity 
made it impossible.

### PR DESCRIPTION
**Pull request by bianchini88**
Closes #1418

### CODE REVIEW

**Comment by bianchini88** [comment]
@sveinugu As agreed, I have produced a draft for the FAIRtracks tool assembly page.

**Comment by korbinib** [comment]
you can add EBI to _data/affiliations.yaml

**Comment by bedroesb** [comment]
^ what Korbian says ;) Concerning the order, I think it is fixed to be alphabetically :/

**Review by korbinib — APPROVED** [review]

**Review by bedroesb — APPROVED** [review]
Just checked locally, looks good. Don't forget to add a news item! ;)

**Comment by bedroesb** [comment]
And to take it out of WIP if ready!

**Comment by sveinugu** [comment]
I just discussed this with @bianchini88, and I would like to review the contents together with him, but I don't have much time right now due an upcoming workshop. So our plan is to sit down together mid-december, hence the reason this is still WIP. Would that be ok?

**Comment by bedroesb** [comment]
off course! Take your time

**Comment by bianchini88** [comment]
@bedroesb @korbinib We are hopefully done for now. Let me know if you want to re-review it since it has changed a bit since the last time. The figure was updated following Korbinian's suggestions above.

**Review by korbinib — APPROVED** [review]

**Comment by korbinib** [comment]
Think this ready to merge?

**Comment by bedroesb** [comment]
I am quickly doing a last local built, 2 sec!

**Comment by bedroesb** [comment]
looks good to me!

**Pull request merged**
