### PR TITLE
Rare disease page draft

### PR DESCRIPTION
**Pull request by PhilipvD**

### CODE REVIEW

**Review by smza — APPROVED** [review]

**Comment by smza** [comment]
@lauportell @pinarpink and @bianchini88.  Apologies I merged this PR without your review because I need screenshots from this page for a talk next week. Please feel free to review and comment if you find any issues.

Thanks
Munazah

**Comment by bedroesb** [comment]
@smza at least add it to the side menu and add a news article than ;) See the editorial checklist in the contribute section

**Comment by bedroesb** [comment]
+ a description needs to be added

**Comment by smza** [comment]
Thanks @bedroesb. will do it tomorrow.

**Pull request merged**
