### PR TITLE
TeSS link update

### LINKED ISSUE #755: Improving the TeSS links based on WP2 hackathon
**Description**
The WP2 hackathon had as goal to improve the linking of training from RDMkit to TeSS>

The working document is this [spreadsheet](https://docs.google.com/spreadsheets/d/1-4qDo3WwsosV52I8p3X6P-yOG-bXy4tT/edit#gid=1167658399)

These queries should be updated on RDMkit

### PR DESCRIPTION
**Pull request by bedroesb**
This PR is based on the proposed changes in the WP2 hackathon. This will close #755

### CODE REVIEW

**Comment by bedroesb** [comment]
@pinarpink many of the rows have `Invite WP2 (NO and other nodes) to discuss their proposal to change/extend RDMkit page tags.` in them as seen here in the [spreadsheet](https://docs.google.com/spreadsheets/d/1-4qDo3WwsosV52I8p3X6P-yOG-bXy4tT/edit#gid=1167658399). Any news on this?

**Comment by bedroesb** [comment]
I updated the keywords based on our discussion this morning:
- we use the short keywords with quotes for life cycle stage pages
- we use the keywords that we putted together in [this spreadsheet](https://docs.google.com/spreadsheets/d/1I-Uyv_W1CsVqaG8JLj1R3bdeBfEjAygw4kv61j775Kg/edit#gid=1019279872) as much as possible (with quotes)
- At this moment TeSS does not search yet in the keywords field but this will be implemented in the future, and if we search on the keywords, we are ready for the future

**Comment by bedroesb** [comment]
@ehj000 do you think I interpreted our call this morning correctly and translated in the correct changes in this PR?

**Comment by ehj000** [comment]
@bedroesb: Yes, that is what we agreed:) Thank you

**Comment by bedroesb** [comment]
@ehj000 thanks for checking!

**Pull request merged**
