### PR TITLE
Better yaml parsing

### PR DESCRIPTION
**Pull request by bedroesb**
By having better yaml parsing we can have more robust readouts from the metadata in the markdown files and it gives us also the option to start validating (#849) the metadata every time somebody makes a pull request/makes changes. This way we can check if page tags that are added are correct, etc ... 

The disadvantage is that the layout of the yaml that gets dumped is more expanded:

New automated style (sorted and expended):

```yml
---
contributors:
- Anne-Françoise Adam-Blondon
- Cyril Pommier
- Daniel Faria
- Paulette Lieby
- Sebastian Beier
- Erwan Le Floch
description: Tool assembly for managing plant genomic data.
faircookbook:
- name: Plant genomic and genetic variation data submission to EMBL-EBI databases
  url: https://w3id.org/faircookbook/FCB061
page_id: plant geno assembly
related_pages:
  your_domain:
  - plants
  your_tasks:
  - metadata
  - data publication
title: Plant Genomics
---
```

Old untouched style:

```yml
---
title: Plant Genomics
contributors: [Anne-Françoise Adam-Blondon, Cyril Pommier, Daniel Faria, Paulette Lieby, Sebastian Beier, Erwan Le Floch]
description: Tool assembly for managing plant genomic data.
page_id: plant geno assembly
affiliations:
related_pages: 
  your_tasks: [metadata, data publication]
  your_domain: [plants]
faircookbook:
- name: Plant genomic and genetic variation data submission to EMBL-EBI databases
  url: https://w3id.org/faircookbook/FCB061
---
```

This behaviour can be explained because the metadata gets parsed and dumped in an automatic way...
Good thing is that I can automate many things than in the future that are now editorial jobs.

### CODE REVIEW

**Comment by bedroesb** [comment]
I would like some feedback on what people think about having it in the new 'yaml layout'

**Comment by bedroesb** [comment]
I am quite used for the title attribute on top for example, but I do like the idea to improve the overall metadata quality

**Comment by floradanna** [comment]
I would need more information to better understand the difference. Maybe an example of how metadata validation will prevent mistake. We could discuss it during a meeting.

**Comment by bedroesb** [comment]
So with every PR we will check that the given page_id exist + are added to the correct section in the related pages metadata block. We will check if in national pages the page_id in the resources are existing ones. 

I can also check instance of in resources of national pages, if it actually exists (if we want this)

**Comment by bedroesb** [comment]
I could off course also do those checks without these changes. Thing is that the current way of parsing the metadata and rewriting it with the DSW and FAIRCookbook links is a bit ... hacky, and although it works perfectly, this new implementation is way cleaner code wise :)

**Comment by bedroesb** [comment]
I guess this was a good exercise but not really needed :)

**Pull request closed without merging**
