### PR TITLE
Add new link to template slides

### PR DESCRIPTION
**Pull request by bedroesb**
These are the template slides created by Xenia

### CODE REVIEW

**Comment by martin-nc** [comment]
The first two slides look a bit odd to me, like the screenshot has accidentally got moved off the page. Is that intentional? Maybe I haven't understood how it will be used.

**Comment by bianchini88** [comment]
I share Martin's concern about the first two slides. Also, in the 3rd one I read "16 current editorial board members" but I see only 15 pictures/names...

**Comment by lauportell** [comment]
I thought the same at the beginning but try to show the slides in presenter mode and it looks very cool!

**Comment by marikapop** [comment]
I would delete a cookie banner on the screenshot on second slide.

**Comment by bedroesb** [comment]
@bianchini88 and @martin-nc like Laura mentioned, it is to be seen in presenter mode, and it is a feature not a bug ;)

**Comment by GilOliveira** [comment]
Love the style and the icons!!
Shouldn't the transition between slides 1-2 be a slide down to revel the rest of the screenshot, instead of a slide right as it is right now?

**Comment by martin-nc** [comment]
I thought a bit the same as @GilOliveira regarding the transition, but I don't think there is a "slide down" option. Still, I'm happy to go with the popular vote on this!

**Comment by GilOliveira** [comment]
I thought a bit the same as @GilOliveira regarding the transition, but I don't think there is a "slide down" option.Oh! I figured it was something that was bound to exist… in that case, I’m all for it! Looks great!

**Comment by bedroesb** [comment]
What if we just take the animation away? ;) Sorry I was not aware the weirdness came from the transition.

**Comment by bedroesb** [comment]
I normally have implemented the feedback and created alternative Opening slides. If somebody can review this, than this can go life!

**Review by martin-nc — APPROVED** [review]
Yes, people have a choice of starts now.

**Pull request merged**
