### PR TITLE
New Policy maker role text

### PR DESCRIPTION
**Pull request by wittigue**
new Policy maker role text based on Google document from contentathon #1276

### CODE REVIEW

**Review by floradanna — APPROVED** [review]
General feedback:
1. Revision of the list of links to training material: e.g. lessons about Data Carpentry might not be super relevant for DS policy officer. Maybe the list could be more focus on the policy.
2. About the paragraph "RDMkit pages", I was wondering if it was really necessary since almost all those page are listed as "related pages" from the metadata of the md page.

**Comment by MijkeJetten** [comment]
For me the page is good to go. One thing: shouldn't we update the contributors list as well to (alone) the Ghent Your Role authors?

**Comment by bedroesb** [comment]
This is a fair question @elixir-europe/rdmkit-editors any opinions?

**Comment by MijkeJetten** [comment]
@bedroesb this is a fully new page, so any other contributors would be weird anyway. For the researcher your role page it might be somewhat different as there was a page before, but the updates are major (hardly any original text left) so I would go for the new contributors only for both pages

**Comment by floradanna** [comment]
@MijkeJetten I am not sure it would be fair. I would keep the names of people that contributed to the previous pages anyway. The new pages are anyway written based on what was there before.

**Comment by MijkeJetten** [comment]
Fine with everything, but we do need the add the new people if they are missing - do we then go for same contributor list for all your role pages, as it was a joint effort in the end.

**Comment by bedroesb** [comment]
I will move it to the dev branch for these changes!

**Pull request merged**
