### PR TITLE
noun project icons for tool assemblies

### PR DESCRIPTION
**Pull request by korbinib**
We have started to use a common icon set from the [noun project ](https://thenounproject.com/ELIXIRCommunications/kit/rdmkit/). (See #635 #594 )

In connection to this I have modified all tool assembly illustrations using the previous EBI icon font accordingly.

@minnami @siirif - Could you please check if this looks OK for you?

### CODE REVIEW

**Comment by bedroesb** [comment]
@korbinib looks good. I assume the plan icon is centered in the circle, yet it looks not centered probably because of the page being the main part of the icon. But this is only a small detail :)

**Comment by korbinib** [comment]
Yes, it's indeed centred . If we want it optically centred we would have to decrease the size of the icon to fit it in the circle. Can do that if you want.

**Comment by bedroesb** [comment]
@martin-nc do you think it is needed to optically center ? :)

**Comment by martin-nc** [comment]
FWIW I'd optically centre them. The 'share' icon looks like it needs nudging left a bit as well, at least to my eyes.

**Comment by korbinib** [comment]
@martin-nc @bedroesb hope this looks OK now?

**Review by bedroesb — APPROVED** [review]

**Pull request merged**
