### PR TITLE
Update marine_metagenomics.md

### PR DESCRIPTION
**Pull request by bianchini88**
Changed link for MIGS/MIMS

### CODE REVIEW

**Comment by bedroesb** [comment]
great! Do you also change the link in the google spreadsheet?

**Comment by bianchini88** [comment]
I modified the .yml file.

**Comment by bedroesb** [comment]
no really, this is overwritten by the google spreadsheet, but will also not hurt :)

**Comment by bianchini88** [comment]
Do you have the link to the spreadsheet readily available?

**Comment by bedroesb** [comment]
Thanks a lot!

**Comment by bianchini88** [comment]
No problem. Shall we just merge or do we wait for others to approve?

**Comment by bedroesb** [comment]
I think we can merge :)

**Comment by Nazeeefa** [comment]
@bianchini88 The link to MIGS/MIMS in the text goes to https://gensc.org/mixs/, and the link for MIxS also goes to https://gensc.org/mixs/ that gives an error 404. 

The links to MIGS/MIMS, mentioned in Relevant tools and resources, goes to page that has information about MIXs https://genomicsstandardsconsortium.github.io/mixs/

I think these should be the correct links for:
- MIXs https://genomicsstandardsconsortium.github.io/mixs/
- MIGS/MIMS https://www.gensc.org/pages/projects/mixs-gsc-project.html (this mentions MIGS/MIMS and also has links to relevant publications)

**Comment by bianchini88** [comment]
@Nazeeefa thank you for spotting this. The links you have found looks very relevant and should be on the page. 
I am annoyed by the fact that the FAIRsharing entries are not correctly annotated... 
According to these https://fairsharing.org/search?q=mixs and https://fairsharing.org/FAIRsharing.va1hck the correct homepages should be http://gensc.org/mixs/ and http://wiki.gensc.org/index.php?title=MIGS/MIMS, but none of these links is resolving... I would very much like to use DOIs from FAIRsharing, but in this case, these would not take the reader anywhere useful...

**Comment by Nazeeefa** [comment]
Yes I also checked on FAIRsharing page and then I had to do my own search, to find https://www.gensc.org/pages/projects/mixs-gsc-project.html

**Pull request merged**
