### PR TITLE
Update fi_resources.md

### PR DESCRIPTION
**Pull request by siirif**
Changed the Icebear description to the Nazeefa's suggestion!

### CODE REVIEW

**Comment by bedroesb** [comment]
Hey Siiri, The icebar tool you added in the main tools table, that is the national tool that is accessible/targeted for all countries right?

If so it can be taken out on the national resource page since we don't duplicate tools.

**Comment by siirif** [comment]
Hi Bert! Ah sorry! I was thinking it would be good advertisement also on the FIN page as there are many FIN collaborators. However, I'm not sure whether it is open for "everyone", but I checked that to use it one can apply Instruct-ERIC access: https://instruct-eric.eu/platform/macromolecular-crystallisation-oulu-finland/) and there are at least 13 member countries in Europe + EMBL.

**Comment by bedroesb** [comment]
@lauportell @Nazeeefa what do you think, do we keep the tool here or in the main tools table?

**Comment by Nazeeefa** [comment]
It's fine to keep it. I see HPC and Fingenious in the list, and those services are for researchers outside Finland too.

**Comment by bedroesb** [comment]
keep it where? :)

**Comment by Nazeeefa** [comment]
National resources page for Finland :D

**Comment by bedroesb** [comment]
@Nazeeefa if you think this is ok, you can approve and merge ;)

**Review by lauportell — APPROVED** [review]

**Pull request merged**
