### PR TITLE
Update cy_resources.md

### PR DESCRIPTION
**Pull request by aoulas**

### CODE REVIEW

**Comment by Nazeeefa** [comment]
Thanks @aoulas for creating the page. I can provide feedback and merge PR once there is more content :) Looking forward to it!

**Comment by bedroesb** [comment]
@aoulas I see you opened #1226 including the same change as this PR, I assume this one can be closed?

**Comment by aoulas** [comment]
Hi Bert,

Please can you update the PR with the latest content.

Many thanks,

Anastasis

Anastasios Oulas, PhD
Associate Scientist | Bioinformatics Department
The Cyprus Institute of Neurology & Genetics
6 Iroon Avenue, 2371 Ayios Dometios, Nicosia, Cyprus | PO Box 23462, 1683, Nicosia, Cyprus
•: +357 - 22 358600 (Switchboard) | ?:+357 - 22 392621 (Direct Line) | •: ***@***.******@***.***> | ?:https://www.cing.ac.cy

[https://www.cing.ac.cy/assets/image/imageoriginal/CING_ENG.png]<https://www.cing.ac.cy/>
[https://www.cing.ac.cy/assets/image/imageoriginal/values_blue.png]

[https://www.cing.ac.cy/assets/image/imageoriginal/telethon.png]<https://www.cing.ac.cy/telethon>[https://www.cing.ac.cy/assets/image/imageoriginal/hrexcellence.png]<https://www.cing.ac.cy/en/about-us/fa/good-practices>[https://www.cing.ac.cy/assets/image/imageoriginal/ergodotisisotitas.png]<https://www.cing.ac.cy/en/about-us/fa/good-practices>[https://www.cing.ac.cy/assets/image/imageoriginal/sir.png]<https://www.cing.ac.cy/en/about-us/fa/good-practices>[https://www.cing.ac.cy/assets/image/imageoriginal/bussinessforclimate.png]<https://www.cing.ac.cy/en/about-us/fa/good-practices>[https://www.cing.ac.cy/assets/image/imageoriginal/facebook.png]<https://www.facebook.com/CING.CSMM/>[https://www.cing.ac.cy/assets/image/imageoriginal/twiter.png]<https://twitter.com/NeuroGeneticsCy>[https://www.cing.ac.cy/assets/image/imageoriginal/youtube2.png]<https://www.youtube.com/user/CINGCSMM>
________________________________

The contents of this email and any attachments are confidential. They are intended for the attention of the named recipient(s) only. If you have received this email in error, please notify the sender immediately and do not disclose the contents to anyone or make copies thereof. Any disclosure, publication, copying, retransmission, distribution or other use of, or taking any action in reliance upon, this e-mail or its attachments by non-authorised persons is strictly prohibited. The CING processes personal data in accordance with the General Data Protection Regulation (EU) 2016/679 (GDPR) and the national legislation, Law 125(I)/2018. Please refer to our Privacy Policy ( https://www.cing.ac.cy/en/privacypolicies ).

This email has been scanned internally by CING systems for viruses, vandals, and malicious content. The CING accepts no liability for any damage caused by any virus transmitted by this email.
[https://www.cing.ac.cy/assets/image/imageoriginal/green_icon.png]please consider your environmental responsibility before you print this email.

________________________________

**Comment by bedroesb** [comment]
@aoulas I think we are working on the wrong pull request, this one only adds contributors. Since I don't know how and where you want this additional content, I think it is better to add it yourself by going to the the files changed tab of the pull request #1226 and clicking on the 3 dots of the file, and than re edit the file. If you encounter any problems please comment on the other PR, I will close this one!

**Comment by aoulas** [comment]
Dear Bert,

I haver made some changes to the #1226<https://github.com/elixir-europe/rdmkit/pull/1226> pull request. Please let me know if it is ok for you to update the content now.

Many thanks for all your kind help,
Best,

Anastasis


Anastasios Oulas, PhD
Associate Scientist | Bioinformatics Department
The Cyprus Institute of Neurology & Genetics
6 Iroon Avenue, 2371 Ayios Dometios, Nicosia, Cyprus | PO Box 23462, 1683, Nicosia, Cyprus
•: +357 - 22 358600 (Switchboard) | :+357 - 22 392621 (Direct Line) | •: ***@***.******@***.***> | :https://www.cing.ac.cy

[https://www.cing.ac.cy/assets/image/imageoriginal/CING_ENG.png]<https://www.cing.ac.cy/>
[https://www.cing.ac.cy/assets/image/imageoriginal/values_blue.png]

[https://www.cing.ac.cy/assets/image/imageoriginal/telethon.png]<https://www.cing.ac.cy/telethon>[https://www.cing.ac.cy/assets/image/imageoriginal/hrexcellence.png]<https://www.cing.ac.cy/en/about-us/fa/good-practices>[https://www.cing.ac.cy/assets/image/imageoriginal/ergodotisisotitas.png]<https://www.cing.ac.cy/en/about-us/fa/good-practices>[https://www.cing.ac.cy/assets/image/imageoriginal/sir.png]<https://www.cing.ac.cy/en/about-us/fa/good-practices>[https://www.cing.ac.cy/assets/image/imageoriginal/bussinessforclimate.png]<https://www.cing.ac.cy/en/about-us/fa/good-practices>[https://www.cing.ac.cy/assets/image/imageoriginal/facebook.png]<https://www.facebook.com/CING.CSMM/>[https://www.cing.ac.cy/assets/image/imageoriginal/twiter.png]<https://twitter.com/NeuroGeneticsCy>[https://www.cing.ac.cy/assets/image/imageoriginal/youtube2.png]<https://www.youtube.com/user/CINGCSMM>
________________________________

The contents of this email and any attachments are confidential. They are intended for the attention of the named recipient(s) only. If you have received this email in error, please notify the sender immediately and do not disclose the contents to anyone or make copies thereof. Any disclosure, publication, copying, retransmission, distribution or other use of, or taking any action in reliance upon, this e-mail or its attachments by non-authorised persons is strictly prohibited. The CING processes personal data in accordance with the General Data Protection Regulation (EU) 2016/679 (GDPR) and the national legislation, Law 125(I)/2018. Please refer to our Privacy Policy ( https://www.cing.ac.cy/en/privacypolicies ).

This email has been scanned internally by CING systems for viruses, vandals, and malicious content. The CING accepts no liability for any damage caused by any virus transmitted by this email.
[https://www.cing.ac.cy/assets/image/imageoriginal/green_icon.png]please consider your environmental responsibility before you print this email.

**Pull request closed without merging**
