### PR TITLE
Update main_tool_and_resource_list.csv

### PR DESCRIPTION
**Pull request by davidcmarkham**
Added 40 entries for the Microbial Biotechnology page
Tags need to be added to these entries

### CODE REVIEW

**Comment by bedroesb** [comment]
@davidcmarkham thank you for contributing! I made this morning an update by bringing the tools from https://docs.google.com/spreadsheets/d/16RESor_qQ_ygI0lQYHR23kbZJUobOWZUbOwhJbLptDE/edit#gid=268211668 to the main toollist on the website, including some that you also want to add. Would it be possible to check which ones were already added this morning?

**Comment by davidcmarkham** [comment]
> @davidcmarkham thank you for contributing! I made this morning an update by bringing the tools from https://docs.google.com/spreadsheets/d/16RESor_qQ_ygI0lQYHR23kbZJUobOWZUbOwhJbLptDE/edit#gid=268211668 to the main toollist on the website, including some that you also want to add. Would it be possible to check which ones were already added this morning?

Sorry! I didn't realise there was a Google spreadsheet for this. I don't see any of the entries already listed here, would it be easier if I just combined our entries onto this sheet?

**Comment by davidcmarkham** [comment]
I can see that I have inadvertently copied and pasted some existing entries on my branch. The first 5 entries, from FigShare to data.world Data License list, can be removed. The rest should be unique entries.

**Comment by bedroesb** [comment]
You are right, I fixed it. The editors will have a look at the tools as soon as possible!

**Comment by davidcmarkham** [comment]
Thanks! We also need a domain tag to add to these entries (for the Microbial Biotechnology page). Is this something that you can create for us?

**Comment by bedroesb** [comment]
yes, how would 'micro biotech' sound like as tag?

**Comment by davidcmarkham** [comment]
Sounds good to me! Thank you
I'll make another pull request to add this tag to the relevant tools on the table

**Comment by bedroesb** [comment]
@davidcmarkham you can do it in this PR if you want! In the files changed you can click on edit file if you click on the 3 dots on you left. I added the tag, so you can start using it.

**Review by bedroesb — APPROVED** [review]

**Pull request merged**
