### PR TITLE
First DS Wizard deep link proposal

### PR DESCRIPTION
**Pull request by rwwh**

### CODE REVIEW

**Review by DanFaria — CHANGES_REQUESTED** [review]
@rwwh maybe it should be stated that the DSW link requires a DSW account to access it.

**Comment by rwwh** [comment]
The deep link should *not* require a DSW account, @DanFaria. If it does now, that is an error somewhere. Did you test it?

**Comment by DanFaria** [comment]
I did test it

image

**Comment by rwwh** [comment]
Thanks, and sorry. This will need a fix on the DSW side (probably a configuration flag in the "researchers" instance). The patch should be unaffected.

**Comment by DanFaria** [comment]
So, we put this patch on hold until you sort things out on the DSW side?

**Comment by rwwh** [comment]
I'm working on it. 

I think it would be good to discuss any other aspects of the patch already, like the general structure of the referral, and how this fits into the future view on page templates. That was the primary reason for me to submit this PR.

**Comment by DanFaria** [comment]
Yeah, sorry for leaving that part out. I do agree with your proposed structure---I was about to accept the pull request when I thought to check the link first :-)
I would like to bring this up in the next editorial board meeting, since this will require updating page templates, but I don't anticipate any issues.

**Comment by MarekSuchanek** [comment]
There was a misconfiguration for public knowledge model previews... it works now.

**Comment by DanFaria** [comment]
I confirm it is working!

**Pull request merged**
