### PR TITLE
add contribution policy

### PR DESCRIPTION
**Pull request by floradanna**
Contribution policy. @martin-nc Please check if the content is ok for you.

### CODE REVIEW

**Comment by bedroesb** [comment]
@martin-nc this will introduce a link behind the collapse button/menu... I don't know what you think of that

**Comment by martin-nc** [comment]
Hmmm - I think there is a lot of information for people to absorb in this section and I wonder how many people will want to look at it, at least on first visit. So there are two types of content in the PR: (1) Ways to contribute and (2) Contribution policy and guidelines. I'd keep the "Ways to contribute" info on the landing page because it seems to me that's what you'd most want to see if you clicked on "Contribute". Maybe I'm wrong, though! I like the fact that you click "Contribute" and right away there are instructions and a form to immediately contribute.

Also, the talk about responsibilities and policies sounds a bit intimidating to me. I'm not sure if it would inspire people to contribute if that's the first thing they saw. I would shorten the title of the landing page (how_to_contribute.md) to "Contribute to the RDMkit" to closer resemble the link text.

It feels to me like the side menu needs refactoring, maybe like:

 - Contribute to the RDMkit (or just "Contribute"): content as now minus the policy stuff.
 - Ways to contribute
    - GitHub way
    - Google Doc way
    - Git way (advanced)
 - Contributor guidelines
    - Overview (I don't think "policy" is quite the right word here): contains the "Contribution policy and guidelines" text plus links to the pages below.
    - Style guide
    - Copyright
    - Markdown cheat sheet
    - Code of Conduct
 - Editorial Board guide
...etc

This "Overview" would be linked to prominently from the landing page. Okay that's all a bit radical. What do you think?

Not sure what the purpose of the "Website overview" is?

**Comment by floradanna** [comment]
Thanks for your suggestions. I see your point. I just have few questions:

- Contribute to the RDMkit (or just "Contribute"): content as now minus the policy stuff.
What would be the content of this page? The paragraphs "Ways of contributing" and "Making a quick suggestion"?
- Ways to contribute.
This section will not have its own "landing page", correct?
- Editorial Board guide.
This section will only have "Editors checklist" as sub-page?

"Website overview" should be useful to see the page_id of all pages, so it should be useful for both contributors (to list related pages) and editors.

**Comment by bedroesb** [comment]
What do you think of:
- Editorial Board (or For the editors, ..)
  - Editorial board guide
  - Editorial checklist

**Comment by martin-nc** [comment]
> What would be the content of this page? The paragraphs "Ways of contributing" and "Making a quick suggestion"?

I'd keep it as it is but replace "Contributor responsibilities" with "Contributors' guidelines", and have a short blurb like "When contributing to the site please bear in mind the Contributor's guidelines [link], which contain the style guide we use as well as a markdown cheat sheet and other information."

> This section will not have its own "landing page", correct?

Yes, correct. 

> This section will only have "Editors checklist" as sub-page?

It depends if we want non-editors to look at the editors' checklist. If we don't then I'd go with @bedroesb's suggestion and put it as a sub-page. I thought we were encouraging everyone to look at it, though? If that's the case it would be easier to find if the page was not in a subsection. 

Anyway, feel free to ignore any of this. Just suggestions.

**Comment by floradanna** [comment]
I kept it simple for now. I have just added the "Ownership of content" paragraph to the current "Contribute" page.

**Comment by bedroesb** [comment]
small steps at a time :smiley:

**Pull request merged**
