### PR TITLE
Add elabFTW to tools list

### PR DESCRIPTION
**Pull request by GilOliveira**
[elabFTW](https://www.elabftw.net/) is a FOSS ELN.

### CODE REVIEW

**Comment by GilOliveira** [comment]
Converted to draft as it looks like my editor is changing the single quotes to double quotes in other entries...

**Comment by GilOliveira** [comment]
Okay, ready to go!

**Comment by GilOliveira** [comment]
> all tools need to be put in context on the RDMkit by describing it within the text.
@bedroesb My objective in adding the tool is I'm working on a PR to update the Portuguese resources page, and we have an instance of elabFTW running, and wanted to link back to a tool page using the `instance_of` property. Would that suffice?

**Comment by bedroesb** [comment]
Sadly you would still have to add it somewhere in a relevant guideline page because that is the rule in other to get it in the main tools table. But indeed once that's done, you can this way describe an instance of the tool in the national page.

**Comment by bianchini88** [comment]
@GilOliveira consider adding a TeSS query to this entry, which would bring people to your own workshop material:
https://tess.elixir-europe.org/materials/ready-for-biodata-management-intensive-course

**Comment by bedroesb** [comment]
@GilOliveira Any news on referencing the tool inside of the RDMkit?

**Pull request closed without merging**
