### PR TITLE
Improved bibliography

### PR DESCRIPTION
**Pull request by bedroesb**
This should fix the remark of @bianchini88  in #1447

### CODE REVIEW

**Comment by bianchini88** [comment]
Hi @bedroesb. Ok, thanks, I will do the same here https://github.com/elixir-europe/rdmkit/pull/1443. We will need to edit all the new BibTeX entries (as they get added). It might be worth documenting this somewhere.

**Comment by bianchini88** [comment]
@bedroesb There is another issue which I am experiencing here https://github.com/elixir-europe/rdmkit/pull/1443. 

When the entry is "Author et al." you obviously get "Author et al." out, but when it is the explicit list of all the authors you get "Author, et al." i.e. with an additional ",". 

Which one do we want? (I suppose the one with the extra comma, given that this come from our general settings and not from manually tweaking the entry on the bib file).

**Comment by bianchini88** [comment]
@bedroesb On top of the matter above, there is also the matter of having full names or only initials. I would say only the initials, but then we need again to manually change the entries in the bib files to kill the full names unless we can change the style somewhere. Maybe @korbinib knows something we do not know?

@martin-nc can you help us take a decision here?
Which one is correct?

Cook, M et al.

or

Cook, M, et al.

**Comment by martin-nc** [comment]
I guess it's a question of choosing a style and sticking to it, although "Cook, M and _et al._" is definitely wrong ("_et_" already means "and", of course). Originally the style guide recommended formatting the bibliography in the Nature style: https://github.com/elixir-europe/rdmkit/blob/c82b1fd8d844f7f5565a20bf8a995fd2531acd86/pages/contribute/style_guide.md

See: https://www.nature.com/srep/author-instructions/submission-guidelines#references

So that would mean:

-  Up top five authors: write all author names e.g. "Cook, M., Bloggs, F., Doe, J. ..."
-  More than five authors: just the first author with "_et al._" e.g. "Cook, M., _et al._ ..."

I'm not sure if we discussed citation styles much. Personally, I prefer less punctuation, like in the [CSE style guide](https://www.scientificstyleandformat.org/Tools/SSF-Citation-Quick-Guide.html), but maybe we should stick with what we said in the style guide originally. Is that going to be practical? I can go through some citations to standardise them.

A good thing about adopting an external style guide like this is that the guide will cover the formatting of different sources (websites, journals, books). I'm not sure how aware we can expect people to be of these difference, but at least we have a reference for ourselves.

**Comment by bianchini88** [comment]
Thank you, @martin-nc"

Note that we do not necessarily have control over the total number of authors, some BibTeX entries are already in the form

Cook, M, et al. 

and I do not think we want to go look for the original paper, count the authors and decide whether they need to be edited back into the BibTeX entry or not.

Note also that in the current implementation of a bibliography on RDMkit, you get only one author in the bibliography even if you have less than five authors in the list. For example, on the ML domain PR I am linking above I have an entry containing:

author = { Susanna-Assunta   Sansone  and  Philippe   Rocca-Serra  and  Mark   Wilkinson  and  Lee   Harland },

resulting in 

Sansone, Susanna-Assunta, et al.

where not only you do not get the full list of 4 authors but you also get the full name and not initials. 

One would think there must be a place where you get to edit these options (.bst?) but I am not sure where to look for it...

**Comment by bianchini88** [comment]
Thank you for all these details, @martin-nc.

I suppose we can try a couple of styles and see which one we like best. 

> Anyway, we probably need to decide if we let the current entries drive the format

What find interesting is that the majority of our entries are of the form   

author={Cook,  M. and et al.},

which makes me think they are all exported from the same source or using the same tool. I see that many are coming from PubMed, which does not seem to offer export in .bib format. So I am not sure how these are actually generated.

**Comment by korbinib** [comment]
I have fixed the bibliography for now. Please See #1454. Also I have made a zotero group for this purpose: https://www.zotero.org/groups/5371154/rdmkit
I suggest to refer to zotero as a tool, to avoid people having to manual creating errors in bibtex.

**Comment by bianchini88** [comment]
@korbinib @bedroesb @martin-nc 

I have merged Korbinian's commit into this. Now, merging this one into master would solve the initial issue (together with #1454 which is merged into master already), now linked to this PR. Now that the Bibtex entries are correct, we can probably address citation and bibliography styles separately (if this is still necessary). We should also document the instructions for the Zotero-centric export of Bibtex.

Shall we go ahead and merge this?

**Review by bianchini88 — APPROVED** [review]

**Comment by bianchini88** [comment]
@martin-nc 

> I guess this is corrected in the Jekyll build?

This is unfortunately not the case. I suppose picking the right style would help, although the one with the missing surname needs to be fixed. 

> It's not clear to me what the workflow is for the contributor. At the moment the Style Guide says, "Add your citations as bibtex to the _bibliography/references.bib file." Are we changing it something like @korbinib 's instructions in https://github.com/elixir-europe/rdmkit/pull/1454#issuecomment-1909864246?

One could argue that *Add your citations as BibTeX to the _bibliography/references.bib file.* is still correct. What changes are the recommendations on how to get better (although not perfect, as you noticed above) BibTeX entries, which should definitely be added to the documentation. We could also think about adding our ideal structure for BiBtex in the documentation.

This PR at least solves that "Author and et al." issue #1447, which is already a big improvement, I would say.

**Review by martin-nc — APPROVED** [review]
Okay, let's go for incremental improvement then!

**Comment by bedroesb** [comment]
@martin-nc and @bianchini88 just some context on how we ended up having the current list: I asked Chat GPT to convert the original list:
```md
[Field, D. et al. (2008) ‘The minimum information about a genome sequence (MIGS) specification’, Nature biotechnology, 26(5), pp. 541–547. doi: 10.1038/nbt1360.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2409278/)

[Ham, T. S. et al. (2012) ‘Design, implementation and practice of JBEI-ICE: an open source biological part registry platform and tools’, Nucleic acids research, 40(18), p. e141. doi: 10.1093/nar/gks531.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3467034/)

[Hecht, A. et al. (2018) ‘A minimum information standard for reproducing bench-scale bacterial cell growth and productivity’, Communications biology, 1, p. 219. doi: 10.1038/s42003-018-0220-6.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6283831/)

[Kuwahara, H. et al. (2017) ‘SBOLme: a Repository of SBOL Parts for Metabolic Engineering’, ACS synthetic biology, 6(4), pp. 732–736. doi: 10.1021/acssynbio.6b00278.](https://pubmed.ncbi.nlm.nih.gov/28076956/)

[Maloy, S. R. and Hughes, K. T. (2007) ‘Strain Collections and Genetic Nomenclature’, Methods in Enzymology, pp. 3–8. doi: 10.1016/s0076-6879(06)21001-2.](https://pubmed.ncbi.nlm.nih.gov/17352909/)

[Parte, A. C. et al. (2020) ‘List of Prokaryotic names with Standing in Nomenclature (LPSN) moves to the DSMZ’, International journal of systematic and evolutionary microbiology, 70(11), pp. 5607–5612. doi: 10.1099/ijsem.0.004332.](https://pubmed.ncbi.nlm.nih.gov/32701423/)

[Sainz de Murieta, I., Bultelle, M. and Kitney, R. I. (2016) ‘Toward the First Data Acquisition Standard in Synthetic Biology’, ACS synthetic biology, 5(8), pp. 817–826. doi: 10.1021/acssynbio.5b00222.](https://pubmed.ncbi.nlm.nih.gov/26854090/)

[Sarkans, U. et al. (2018) ‘The BioStudies database—one stop shop for all data supporting a life sciences study’, Nucleic Acids Research, pp. D1266–D1270. doi: 10.1093/nar/gkx965.](https://pubmed.ncbi.nlm.nih.gov/29069414/)

[Spidlen, J. et al. (2021) ‘Data File Standard for Flow Cytometry, Version FCS 3.2’, Cytometry. Part A: the journal of the International Society for Analytical Cytology, 99(1), pp. 100–102. doi: 10.1002/cyto.a.24225.](https://pubmed.ncbi.nlm.nih.gov/32881398/)

[‘Standards for Reporting Enzyme Data: The STRENDA Consortium: What it aims to do and why it should be helpful’ (2014) Perspectives in Science, 1(1-6), pp. 131–137. doi: 10.1016/j.pisc.2014.02.012.](https://www.sciencedirect.com/science/article/pii/S2213020914000135)

[Tellechea-Luzardo, J. et al. (2020) ‘Linking Engineered Cells to Their Digital Twins: A Version Control System for Strain Engineering’, ACS synthetic biology, 9(3), pp. 536–545. doi: 10.1021/acssynbio.9b00400.](https://pubmed.ncbi.nlm.nih.gov/32078768/)

[Ten Hoopen, P. et al. (2015) ‘Marine microbial biodiversity, bioinformatics and biotechnology (M2B3) data reporting and service standards’, Standards in genomic sciences, 10, p. 20. doi: 10.1186/s40793-015-0001-5.](https://pubmed.ncbi.nlm.nih.gov/26203332/)

[Zhang, M. et al. (2017) ‘SBOLDesigner 2: An Intuitive Tool for Structural Genetic Design’, ACS synthetic biology, 6(7), pp. 1150–1160. doi: 10.1021/acssynbio.6b00275.](https://pubmed.ncbi.nlm.nih.gov/28441476/)
```

To bibtex format. It is possible that he himself during the conversion started adding the "and".

**Comment by bianchini88** [comment]
@bedroesb I see, and this makes me think that the ML people did the very same thing for some of their papers (not all). So chat GPT is the "mysterious tool" that was used to generate these. It seems so obvious now... 

So, just to make it clear, the "and et al." thingy was just wrong and it was the reason why I started looking into this. It turned out we did not follow best practices regarding bib entries and Korbinian pointed to a much better way of handling this.

**Pull request merged**
