### PR TITLE
Update fi_resources.md

### PR DESCRIPTION
**Pull request by siirif**
Tried to add one FI RDM tool to the table + a spelling mistake. I also added the tool in the main google sheet. I'm not sure how it was marked that it is a FI resource.

### CODE REVIEW

**Comment by bedroesb** [comment]
@siirif almost 100% correct,   `- name: IceBear` line had 2 extra spaces. I know it is not an easy one to edit YAML in the GitHub Editor :/

**Comment by bedroesb** [comment]
@lauportell and/or @Nazeeefa will have a second look :)

**Comment by bedroesb** [comment]
@siirif Just one question, the tool you added to the main tools table, did you take that one out of the national one? You can refer to tools in the main tools table by adding listing its name using this syntax in the metadata of the page:

```yml
ref_to_main_resources: 
  -  Resource name
```

**Review by Nazeeefa — COMMENTED** [review]
Looks good to me! For description, I suggest following rephrasing: 

"A browser-based Research Data Management tool for protein cyrstallization that offers flexible crystal fishing workbench, no-typing submission for crystal shipment, and linking crystals and datasets including PDB depositions."

I mentioned RDM in full for better SEO of the page. I understand the description needs to be short so this should be enough? Feel free to discard this suggestion if you have permission from IceBear to use the exact description as theirs.

**Comment by siirif** [comment]
@Nazeeefa I like your suggestion!

**Comment by siirif** [comment]
How does this pull request go forward? It says "Merging can be performed automatically with 1 approving review."?

**Comment by bedroesb** [comment]
@siirif and @lauportell this PR was not merged since the suggestion from me and Nazeefa was not implemented or am I wrong?

**Pull request merged**
