### PR TITLE
Moving to the new way of tagging tools in content

### PR DESCRIPTION
**Pull request by bedroesb**
Tools will be described in the main `tools and resources yaml file`:

image

And be linked from the content using 

`{% tool "tool-id" %}`

This will be visualized in the content like this:

image

Still on the TODO:

- [x] Replace tool links in the text with the new snippet
- [x] Add missing tools to the main yaml file
- [x] https://github.com/bedroesb/rdmkit/blob/demo/_data/tool_and_resource_list.yml replace
- [x] Adapt content so tools get mentioned at least once @ rdmkit
- [x] Agree on how to handle country specific tools
- [x] in national pages, change ref_to_main_resources so that it makes use of ID
- [x] update instance_of to make use of the tool ID
- [x] agree on (not) having backwards compatibility for old way of having related pages at tools/spreaadsheet
- [x] Update to spreadsheet convertor script to work with the yaml file so the yaml file gets updated with FAIRsharing/TeSS and Bio.tools IDs automatically
- [x] Nicer/better dropdowns for the tool information
- [x] Make the tools in tools table alphabetically.
- [x] Add new way of tagging the tools to the ELIXIR Toolkit Theme
- [x] Update documentation in how to add a new tool or resource
- [x] Make the snippet more forgiving
- [x] Adding a linter to check for:
  - [x] id is kebab-case
  - [x] Description does not contain colon
  - [x] URL works
  - [x] Make sure that id linked in "instance_of" exists in the main yaml file

### CODE REVIEW

**Comment by bedroesb** [comment]
ERROR: Undefined tool ID: ELIXIR Core Data Resources in pages/your_tasks/existing_data.md

**Comment by bedroesb** [comment]
XNAT assembly does not seem to have a working tools table

**Comment by bedroesb** [comment]
This will also close #1114

**Review by martin-nc — APPROVED** [review]
Looks good to me!

**Comment by bedroesb** [comment]
This is a big moment, lets gooo :rocket:

**Pull request merged**
