### PR TITLE
Adding introduction to the national resources page

### PR DESCRIPTION
**Pull request by bedroesb**
@Nazeeefa thanks for this introduction!

### CODE REVIEW

**Comment by floradanna** [comment]
Thanks Nazeefa.
Do you think we could highlight a bit more the fact that these national resources are meant to help readers seeking country-specific advice?
Here my suggestion, based on yours:

Although RDM tasks that needs to be addressed are quite universal, the practical solutions available are ofter dependent on institute- or country-specific policy, funders and infrastructures. 

Here,  we point to national (country-specific) information resources such as local funding agencies, research councils, local policies for open science, national regulations on data ethics, domain-specific infrastructures and tools. 

These country-specific basic overviews about RDM will help readers to seek national advice and could be an inspirational guide for other countries to implemet and promote data management practices at national level.

**Comment by Nazeeefa** [comment]
Thank you @floradanna
Yes, sounds good and here is the updated text with your suggestions included:

> To be able to effectively address RDM tasks, it is important to take into account existing practical solutions that are often dependent on institute- and country-specific policies, funders, and infrastructures.
> 
> Here, we point to non-exhaustive collection of national (country-specific) information resources such as local funding agencies and research councils, and information on local policies for open science, national regulations on data ethics, and domain-specific infrastructures and tools.
> 
> These country-specific RDM overviews will help readers to seek national advice and could be an inspirational guide for other countries to implement and promote data management practices at national level.

If you want, you can replace first sentence with "To carry out RDM tasks FAIRly and effectively, it is important to consider not only common global solutions but also existing (or national, as suggested initially) solutions..."

**Comment by bedroesb** [comment]
I like your suggestion @Nazeeefa 

I changed it now to: 


To carry out RDM tasks FAIRly and effectively, it is important to consider not only common global solutions but also existing, national solutions, that are often dependent on institute- and country-specific policies, funders, and infrastructures.

Here, we point to non-exhaustive collection of national (country-specific) information resources such as local funding agencies and research councils, and information on local policies for open science, national regulations on data ethics, and domain-specific infrastructures and tools.

These country-specific RDM overviews will help readers to seek national advice and could be an inspirational guide for other countries to implement and promote data management practices at national level.

**Comment by bedroesb** [comment]
Since the newsletter is Monday I will merge this, if people want to change the content they can open a PR :)

**Pull request merged**
