### PR TITLE
Adding history button + tooltips

### LINKED ISSUE #766: Show update dates in pages
**Description**
Show update dates in pages.

### PR DESCRIPTION
**Pull request by bedroesb**
Next to the edit me button we will also have a history button.

This can be with or without text:
Screenshot from 2021-11-24 14-31-25
Screenshot from 2021-11-24 14-45-08
Screenshot from 2021-11-24 14-52-00

### CODE REVIEW

**Comment by lauportell** [comment]
Nice! I think it looks better with the text appearing when you hover over the button

**Comment by bedroesb** [comment]
great, ok I have 2 approvals, I guess I can merge this :D

**Review by floradanna — APPROVED** [review]

**Comment by floradanna** [comment]
Having the text "edit me" and "history" always visible is more explicit, but I don't have strong preferences.

**Comment by bedroesb** [comment]
@floradanna I agree, but it also took quite some space... I also don't have strong preferences

**Comment by bedroesb** [comment]
Let's have a look how this feels, we can always switch it back

**Pull request merged**
