### PR TITLE
Update data_management_plan.md

### PR DESCRIPTION
**Pull request by xiaoranzhou**
Added DataPLAN to the tool list. Not sure if this is the correct text location

### CODE REVIEW

**Comment by floradanna** [comment]
Thank you very much for your contribution. 

The editors will look into it.

**Comment by xiaoranzhou** [comment]
> Thank you very much for your contribution.
> 
> The editors will look into it.

Thanks  a lot

**Comment by Nazeeefa** [comment]
I guess this PR can be closed? as it will replace other PR that will involve adding DataPlan to Plant (your domain) page and Germany (national resources) page.

**Comment by floradanna** [comment]
I would prefer to keep it open until the other changes are made (maybe by @wittigue and @sebeier), on the national page for Germany and plant sciences domain.

**Review by Nazeeefa — APPROVED** [review]

**Comment by bedroesb** [comment]
@erlefloch What do you think of adding DataPlan to the plant page?

**Comment by erlefloch** [comment]
@bedroesb currently the [plant sciences page](https://rdmkit.elixir-europe.org/plant_sciences) does not describe DMPs , I think it was meant to avoid duplicating information. 
ping @afablondon

**Comment by floradanna** [comment]
It is true that a paragraph about DMP is missing in the plant page, but I think that it could be easily added since there is actually a DMP tool dedicated to plant research. A short paragraph will already be enough. However, if the tool is institute specific (it can only be used by specific institute/countries), it might be best to only describing it on the National page.
I don't know if it could be included in the plant tool assembly.

I guess that the other domains do not have a paragraph about DMP because they just use the generic DMP tools (DMPonline, DSW etc) mentioned in the generic task page, and/or institute specific template or questionnaire, mentioned in National pages.

**Comment by sebeier** [comment]
Currently, it supports DMPs for Horizon 2020, Horizon Europe and the German BMBF and DFG. The main focus during development was to be able to be used with German funding agencies but was also extended to include other European funders.

**Comment by erlefloch** [comment]
Draft PR : https://github.com/elixir-europe/rdmkit/pull/1246

**Comment by erlefloch** [comment]
> Draft PR : #1246

now ready for merging I think

**Pull request merged**
