### PR TITLE
Update plant_phenomics_assembly.md

### PR DESCRIPTION
**Pull request by erlefloch**
removal of:
- dropdowns lists of links not displaying correctly
- the link to geno toolkit (not allowed unfortunately)

### CODE REVIEW

**Comment by erlefloch** [comment]
@bedroesb these are the updates that we just discussed

**Review by korbinib — APPROVED** [review]

**Comment by bedroesb** [comment]
I agree it is unfortunate for the link towards the other Assembly/. I can always bring it up in the editorial meeting. Thanks!

**Review by bedroesb — APPROVED** [review]

**Comment by bedroesb** [comment]
@erlefloch I see you took them fully out, but mabe we can refurbish the content in an other format ... @korbinib Do you think we should keep the content of the dropdowns?

**Comment by korbinib** [comment]
Maybe they could be split between tools, references and training material?

**Comment by erlefloch** [comment]
> Maybe they could be split between tools, references and training material?

good idea !

**Comment by erlefloch** [comment]
@korbinib @bedroesb I have splitted the content.

**Comment by bedroesb** [comment]
Let's merge.

**Pull request merged**
