### PR TITLE
Update se_resources.md

### PR DESCRIPTION
**Pull request by YvonneKallberg**
Review of all links and resources, and update where necessary

### CODE REVIEW

**Comment by YvonneKallberg** [comment]
I changed links to resources directly in the page, is this the way to do it or should it be somewhere more central in the main tool & resource page?

**Comment by Nazeeefa** [comment]
@YvonneKallberg The links should also be mentioned/updated here in tools and resources list which can be found in `_data/tool_and_resource_list.yml`.

**Comment by Nazeeefa** [comment]
Ja, only "The European Genome-phenome Archive (EGA)" is linked to the tools and resources table. I thought national covid-portals and national EGA instances are also considered tools/resources, that's what I was thinking of in my previous comment - e.g. I see FEGA Finland and Norway in Tools and Resources list https://rdmkit.elixir-europe.org/all_tools_and_resources and Sweden's Covid portal is also mentioned there https://covid19dataportal.se/

**Comment by bedroesb** [comment]
@Nazeeefa this should not be the way of doing things. National instances are listed only on national pages, and not in the main tools and resources page. If this is the case, than this is wrong and this should be fixed.

**Comment by bedroesb** [comment]
I migth have understand you wrong @Nazeeefa, I do not find FEGA back in https://github.com/elixir-europe/rdmkit/blob/master/_data/tool_and_resource_list.yml ?

**Comment by bedroesb** [comment]
Some information: 
- the overview with all tools and resources in the RDMkit, https://rdmkit.elixir-europe.org/all_tools_and_resources, contains both the tools from the main yaml file and the ones listed in the country pages.
- If you update your national tools in the metadata of your national page, they will also be updated in the https://rdmkit.elixir-europe.org/all_tools_and_resources page
- In the National pages we describe resources tailored to users in that country (most of the time they also have a national domain)

**Comment by bianchini88** [comment]
@bedroesb 
> I do not find FEGA back in https://github.com/elixir-europe/rdmkit/blob/master/_data/tool_and_resource_list.yml ?

The central EGA is indeed in the table (id: the-european-genome-phenome-archive)

The federated nodes should be on the national pages. 
On the NO page we have:

>  - name: Federated EGA Norway node

Which I believe is correct. A similar entry is present on the page for Finland, 
so I believe there is no issue with the current "positioning" of tools.

A question: the tools on national pages do not seem to have an "id" field. Is there a reason for that?

**Comment by Nazeeefa** [comment]
> Some information:
> 
> * the overview with all tools and resources in the RDMkit, https://rdmkit.elixir-europe.org/all_tools_and_resources, contains both the tools from the main yaml file and the ones listed in the country pages.

Yes that's what I mean when I wrote "I see FEGA Finland and Norway in Tools and Resources list https://rdmkit.elixir-europe.org/all_tools_and_resources"
 
> * If you update your national tools in the metadata of your national page, they will also be updated in the https://rdmkit.elixir-europe.org/all_tools_and_resources page

Yep, makes sense!

**Comment by YvonneKallberg** [comment]
Does this mean that I do not have to do anything additionally to what I have done? I've updated links in the metadata header of the national page, and that is it?

**Review by Nazeeefa — APPROVED** [review]

**Comment by Nazeeefa** [comment]
@YvonneKallberg thank you! I think this is it, however I am wondering it might be useful to mention FEGA Sweden (https://fega.nbis.se/) in the metadata header of the page.

**Comment by YvonneKallberg** [comment]
I've added a metadata post for FEGA-SE now

**Review by Nazeeefa — APPROVED** [review]

**Pull request merged**
