### PR TITLE
Possible improvements to transfer

### PR DESCRIPTION
**Pull request by alaninmcr**
Munazah - can you look at this

### CODE REVIEW

**Comment by bedroesb** [comment]
@alaninmcr I see you made edits to the yaml file. Sadly this gets overwitten by our github actions because our main tool file is the [csv](https://github.com/elixir-europe/rdmkit/blob/master/_data/main_tool_and_resource_list.csv) more info on how to add a tool can be read here: https://rdmkit.elixir-europe.org/tool_resource_update.html

**Comment by alaninmcr** [comment]
Thanks Bert. I'll do it tomorrow

**Comment by alaninmcr** [comment]
I think it has been fixed now.

**Review by bedroesb — APPROVED** [review]

**Comment by bedroesb** [comment]
@smza can this be merged?

**Pull request merged**
