### PR TITLE
Apply typography suggestions

### PR DESCRIPTION
**Pull request by bedroesb**
### H1 updates
- [x] Default colour
### H2 updates
- [x] Keep Exo 2 
- [x] margin-top: 2.5 rem
- [x] margin-bottom: 0.5 rem
- [x] Font weight: ~500~ 600
- [x] Font-szie: 2.2 rem
### H3
- [x] font-weight : 600
- [x] Font-size: 1.5 rem

### CODE REVIEW

**Comment by bedroesb** [comment]
These are discussed changes from our monthly UX meetings

**Comment by bedroesb** [comment]
definitely possible, the problem is a bit that we use font weights that are not always available with the fonts used by people...

**Comment by bedroesb** [comment]
@martin-nc for example with the IDTk for me the jump is to big:
image

image

But this is just my opinion...

**Comment by bedroesb** [comment]
Maybe I just have to get used to it :)

**Comment by martin-nc** [comment]
Hmmm - I hadn't thought about people choosing different fonts for the toolkit theme. If that's the case, you might want to stick to 400 and 700 for that theme, and keep it simple. Each font should definitely have those! Unless it's a display or monospace font, of course, but you can't account for that. 

So then the questions is: do we stick to the same rules for the RDMkit? I don't think that's necessary. Once the theme is out there it's a free-for-all, and you can't enforce a law about how people should use fonts in it. For the RDMkit, I'd maybe make the `h2` 600, on reflection. It's not such a big change but it's more in keeping with the new `h3` rules, and it looks less clunky than the current 700. What do you think?

**Comment by bedroesb** [comment]
@martin-nc I agree, I changed them to 600! I was thinking of merging these changes for now and doing rethinking the theme on its own another time :thinking:

**Pull request merged**
