### PR TITLE
Improve navigation by aligning the related pages with navigation tiles

### PR DESCRIPTION
**Pull request by bedroesb**
Section navigation tiles:

image

New related pages:

image

New "more information" section with collapasables:

image
image

## **[Preview the changes here](https://bedroesb.github.io/rdmkit/data_analysis)**

### CODE REVIEW

**Comment by bedroesb** [comment]
The idea is to make a recognizable way of navigating, possibly through tiles (can change in the future)

**Comment by bedroesb** [comment]
@martin-nc This is ready for review! There are just 2 known problems where I did not find a quick fix for:

- https://bedroesb.github.io/rdmkit/lu_resources#related-pages 
  The selector does not work when only one element is available ... Putting it in a wrapper div is not the best option because it is possible that there are no "more information" sections
  ```scss
  .info-collapse {
    &:first-of-type {
        margin-top: $spacer * 4;
    }
  ```
  I also did not get the `last-of-type` selector working to draw a border at the bottom of the last collapsable
- My background trick does not work when the page content does not fil the entire screen: https://bedroesb.github.io/rdmkit/404


Link to the sass file: https://github.com/ELIXIR-Belgium/elixir-toolkit-theme/blob/related-pages-cut/assets/css/main.scss#L889

**Comment by bedroesb** [comment]
@elixir-europe/rdmkit-editors After many many commits and even more discussions, I think I am ready for your approval/feedback on the new design of the More information tiles, preview it here: https://bedroesb.github.io/rdmkit

**Comment by bedroesb** [comment]
@marikapop the "training in TeSS" is easily customizable and can be done outside this PR. When it comes to a general training blurb, this should be part of the ETT changes. DO you have there anything in mind that is not TeSS only?

**Comment by marikapop** [comment]
> @marikapop the "training in TeSS" is easily customizable and can be done outside this PR. When it comes to a general training blurb, this should be part of the ETT changes. DO you have there anything in mind that is not TeSS only? Or were you specifically talking about the training buttons itself :)

No. I do not have any other comment.

**Review by marikapop — CHANGES_REQUESTED** [review]
I cannot judge technical changes, just found a typo

**Review by martin-nc — APPROVED** [review]
Looks good now, except just the typo Marina spotted. Thanks!

**Comment by bedroesb** [comment]
Ok lets pull the trigger and improve later on!

**Pull request merged**
