### PR TITLE
Make sure contribute pages do not show up when the search is used

### PR DESCRIPTION
**Pull request by bedroesb**
Screenshot from 2022-11-10 17-33-10

### CODE REVIEW

**Comment by bedroesb** [comment]
Screenshot from 2023-03-10 16-46-53

The people have voted and the answer is no! Lets close the PR :)

**Review by Nazeeefa — APPROVED** [review]

**Comment by Nazeeefa** [comment]
From screenshot, it shows 6 people voted for option 2.

**Comment by Nazeeefa** [comment]
Ok so the voting is "no, it should show up" I got confused that answer is no as in "no contribute page showing up" :D let's merge and close ✅🎉

**Comment by bedroesb** [comment]
no merge! My change in this PR was to hide the results "Make sure contribute pages do not show up when the search is used" :)

**Comment by bedroesb** [comment]
I still don't understand why one want the contribute pages to show up if he is looking for data management content. It is only useful for contributors, but that is the minority. For the other ones it is just confusing.

**Comment by Nazeeefa** [comment]
Haha stop the merge! had a tough week and got confused, sorry. I am also in favour of contributors page not showing up, but contributors page is also easy to miss or can be easily overlooked so it's good if it is included in search bar.

**Pull request closed without merging**
