### PR TITLE
Update marine_metagenomics.md

### PR DESCRIPTION
**Pull request by Nazeeefa**
Updated links for MIXs and MIGS/MIMS as mentioned here https://github.com/elixir-europe/rdmkit/pull/910

### CODE REVIEW

**Review by bianchini88 — APPROVED** [review]

**Comment by bianchini88** [comment]
I found by chance [this page here](https://www.gensc.org/pages/standards-intro.html),
which looks also like something we could link for MIxS.

**Comment by Nazeeefa** [comment]
Yep, I saw/found it too but wasn't sure how to link it in text - on a second thought, maybe it's sufficient to link it since it mentions https://genomicsstandardsconsortium.github.io/mixs/ however, the link is not-so-easy-to-find hyperlink word "here"..

**Comment by Nazeeefa** [comment]
@bedroesb Good to merge, for now. Thanks for asking :)

**Comment by bedroesb** [comment]
Great!

**Pull request merged**
