### PR TITLE
Creating Costs for Data Management page

### PR DESCRIPTION
**Pull request by Nazeeefa**
**Costs for Data Management**
New 'Your Tasks' page that addresses costing of data management; how to estimate costs, and types of costs that should be considered. The page covers considerations and solutions, with a list of questions that could help to understand possible costs and their sources.

Are there existing pages in the RDMkit website related to the requested page?
For related pages, the authors suggested to add 'Your Tasks' page on Data Management Plan and 'Data life cycle: Planning' page. According to the [editorial board guide](https://rdmkit.elixir-europe.org/editorial_board_guide#related-pages), only Tool Assembly pages can be added as related pages. Therefore, it may be helpful to mention pages that address e.g. storage and computing resources, such as [NeLS tool assembly](https://rdmkit.elixir-europe.org/nels_assembly) and [CSC tool assembly](https://rdmkit.elixir-europe.org/csc_assembly).

cc @siirif @minnami

### CODE REVIEW

**Comment by Nazeeefa** [comment]
Hi! In addition to the feedback I posted in the GitHub issue, I suggest to rephrase some questions to sentences, and structure questions and answers in a way so that it is easy to differentiate between the two - one way to do this is to add 1-2 sentence before a question, for example:

> File formats: Data analysis sometimes involve data conversion, that changes the structure in data organisation. Converting data to a different (open or standard) format for sharing or preserving data can incur costs, and therefore, it is important to ask: is there additional software or hardware required for data conversion? How much additional space is required to store new files? Does converted data need to be stored elsewhere, and do the source files need to be transferred too? 

Just an example :) as I understand, some parts of text were a bit difficult to read with just questions. Also, it would be helpful to rephrase or expand upon following sentences a bit:
- "Have you made good documentation documents about what have done, and do you have README files explaining your data files?"
- "software might cause costs"

Hope you find this useful and thanks again for creating this page.

**Comment by floradanna** [comment]
Thanks for the contribution. I have the following remarks.

- Add this page’s id to plan page (in life cycle section)
- Do not capitalize the first word after the colon unless it is a proper noun or a quote. Please adapt.
- I am not sure if there is a better way to list questions in a sentence ("For example, would you need a dedicated data manager?, should roles and responsibilities about various data management activities be allocated?, do you..."). Maybe there shouldn't be comas and the first letter after the "?" should be capital: _For example, would you need a dedicated data manager? Should roles and responsibilities about various data management activities be allocated? Do you..._  @martin-nc what do you think?
- Maybe the DSW storage costs evaluator could be listed as well: https://storage-costs-evaluator.ds-wizard.org. Would it be better mentioned in "more info section as link to ELIXIR resources"?
- About "Personal costs of Data Steward as an eligible cost in many projects. (FTE limitation)", I am not sure if it would be better to write "Personnel costs for data stewards is an eligible cost in many projects, although with limitations on the number of full time employee (FTE). Check if this cost is eligible in your grant.

**Comment by Nazeeefa** [comment]
Thanks @floradanna, I addressed most comments and updated the page for authors to take care of the rest. Regarding DSW storage costs evaluator, I have included it in main text. It should definitely be mentioned under 'Relevant tools and resources' :)

My feedback regarding cost calculators: the correct page for TU Delft data management costing tool is https://docs.google.com/forms/d/e/1FAIpQLSfwOQmt6KMGDHLPI_3E0CbTydAl_xHMeooftTPT7PZlaPAZDg/viewform and it is only for TU Delft staff/researchers (maybe it should be listed in tools and resources?). The link, that is currently mentioned, gives general information on data management costs https://www.tudelft.nl/en/library/research-data-management/r/plan/data-management-costs - to make a sense of keeping this link in main text, I rephrased the opening sentence to "Some organisations have created tools, **for their users**, to help formulate and budget data management costs". I suggest to add both the UK and TU Delft costing tools under 'national_resources' attribute.

**Review by floradanna — APPROVED** [review]

**Comment by bedroesb** [comment]
Don't forget to add a newsitem and to add the tools to the tools table!

**Comment by bedroesb** [comment]
Woohoow, I will go and update the tools!

**Pull request merged**
