### PR TITLE
adding CSC tool assembly

### PR DESCRIPTION
**Pull request by floradanna**
Adding CSC tool assembly

@siirif @minnami I made a dedicated paragraph for "how to access" and changed few words for formatting. Please check if everything is correct and ok with you.

@bedroesb Can you please [make and add the image](https://cscfi-my.sharepoint.com/:p:/g/personal/sfuchs_csc_fi/EUOsTGR2ezVIqGwkIY_R4swBYm-2o3UJjLF8YjtsqgicVg?rtime=4pg5hQog2Ug)? Let me know if tags and tools and page name are correct.

### CODE REVIEW

**Comment by bedroesb** [comment]
@floradanna the script is failing because I already added the tools with the tag `CSC` in capital. Which one do we take? Because IDP and DMP etc are in capital ...

**Comment by minnami** [comment]
Thanks @floradanna, looks good to me!

**Comment by siirif** [comment]
Hi! Thank you so much Flora and Bert for your help with this page! I wanted to add couple of words and take one out, but as this not yet on a branch I cannot modify...  D: 

I wanted to add the longer name "Sensitive Data Submit (SD Submit), when it was mentioned the first time and take the word "European" off and just leave "ant their collaborators". 

"This summer, CSC will be releasing beta versions of new services for sensitive data management: Sensitive Data Desktop (SD Desktop) and Sensitive Data Connect (SD Connect). **Sensitive Data Submit (SD Submit)** will be available later this year. The new Sensitive Data Services are designed to facilitate collaborative research across Finland and between Finnish academics and their **European** collaborators. [SD Desktop](https://research.csc.fi/-/sd-desktop) is a service that allows a user and their authorized colleagues to access a private computing environment workspace via a web browser and analyze the data within a secure cloud. [SD Connect](https://research.csc.fi/-/sd-connect) allows you to collect, organize and share your encrypted sensitive data in a secure manner via web browser."

**Review by korbinib — APPROVED** [review]

**Review by korbinib — APPROVED** [review]

**Review by bedroesb — APPROVED** [review]

**Comment by korbinib** [comment]
Do we want to unify the appearance of theses illustrations? (Provided we want to stick with example stemming from NeLS?)

**Comment by siirif** [comment]
Korbinian, I wast trying to use your template, but it was not possibly so I made my own trying to do it in a similar manner!

**Comment by floradanna** [comment]
@korbinib we could work on the image during the contentathon maybe. I also have few suggestions, like aligning the names of each step with the RDMkit life cycle stage name and problem name.

**Comment by siirif** [comment]
I'm up to anything, but cannot join the next contentahon! However, I don't have any picture modification tools on my laptop, so I can only do magic with power point :D But I'm happy to modify the CSC picture, if there will be a new template we can fit into!

**Comment by korbinib** [comment]
@floradanna  yes there might be some alignment necessary if we want to use this as a template in future. I am a bit concerned we might preempting the templating here.  Consistent use of icons would be another topic -  @bedroesb ?

**Comment by bedroesb** [comment]
@korbinib good point. When we decide on a general icon set we might want to reflect this in our images + we also might want to make use of the same color pallet + fonts.... in the images we generate. So I expect we will restyle all of them in the future to be consistent.

**Comment by korbinib** [comment]
Suggest to move the discussion to #594

**Pull request merged**
